# Configuration Settings for ZED-F9P device
debug: 1                 # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM1    # ZED-F9P rover serial port
frame_id: gps

config_on_startup: false # use chip config

uart1:
  baudrate: 38400       # serial port baudrate
  in: 32
  out: 3

# Enable u-blox message publishers
publish:
  all: true
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true
